import LocalizedStrings from 'react-localization';

const Localization = new LocalizedStrings({
    "en-GB": {
        /* Menu */
        dashboard: "Dashboard",
        content: "Content",
        article: "Article",
        comment: "Comment",
        page: "Page",
        managmentCategories: "Managment categories",
        tag: "Tag",
        customize: "Customize",
        component: "Component",
        setup: "Setup",
        basic: "Basic",
        email: "Email",
        push: "Push",
        advanced: "Advanced",
        user: "User",
        personalInformation: "Personal Information",
        /* services/api */
        errorInRequeset: "Request an error. Please try again later",
        /* components/bootstrap/* */
        home: "Home",
        enterContentHere: "Enter the content here",
        /* views */
        DotNetBlog: "DotNetBlog",
        changePassword: "Change password",
        logoff: "Logoff",
        userImage: "User Image",
        greetingUser: "Welcome {0}",
        siteNavigation: "Site navigation",
        /* views/dashboard */
        pleaseEnterTitle: "Please enter the title",
        pleaseEnterContent: "Please enter the content",
        draftWasSavedSuccessfully: "Draft was saved successfully",
        saveDraftQuickly: "Save the draft quickly",
        title: "Title",
        save: "Save",
        latestComments: "Latest comments",
        empty: "Empty",
        recentDrafts: "Recent drafts",
        statistics: "Statistics",
        numberOfArticlesPublished: "Number of articles published",
        numberOfPagesPublished: "Number of pages published",
        savedDrafts: "Saved drafts",
        numberOfPages: "Number of pages",
        approvedComments: "Approved comments",
        pendingComments: "Pending comments",
        junkComments: "Junk comments",
        /* views/content */
        operationSuccessful: "Operation successful",
        toView: "To View",
        add: "Add",
        name: "Name",
        pendingReview: "Pending for review",
        accepted: "Accepted",
        rejected: "Rejected",
        accept: "Accept",
        reject: "Reject",
        all: "All",
        pendings: "Pendings",
        date: "Date",
        author: "author",
        status: "Status",
        pleaseEnterCategoryName: "Please enter a category name",
        description: "Description",
        editCategory: "Edit category",
        addCategory: "Add category",
        pleaseEnterPageTitle: "Please enter the page title",
        pleaseEnterPageContent: "Please enter the page content",
        theTitleOfArticle: "The title of the article",
        alias_optional: "Alias(optional)",
        keywords: "Keywords",
        pageDescription: "Page description",
        publish: "Publish",
        cancel: "Cancel",
        cancelThePublish: "Cancel the publish",
        goToThePage: "Go to the page",
        parent: "Parent",
        setAsHomePage: "Set as homepage",
        isDisplayedInTheList: "Is displayed in the list",
        pleaseEnterTheName: "Please enter the name",
        editTheTag: "Edit the tag",
        enterTheTitleOfArticle: "Please enter the title of the article",
        enterTheContentOfArticle: "Please enter the content of the article",
        allowComment: "Allow comment",
        summary: "Summary",
        goToArticle: "Go to article",
        category: "Category",
        showAlias: "Show alias",
        showSummary: "Show summary",
        showDate: "Show date",
        draft: "Draft",
        sorting: "Sorting",
        published: "Published",
        pleaseFillInTheReply: "Please fill in the reply",
        reply: "Reply",
        replyToComment: "Reply to comment",
        time: "Time",
        /* view/user */
        pleaseTypeYourEmail: "Please type your email",
        pleaseTypeCorrectEmailAddress: "Please type correct email address",
        pleaseEnterNickname: "Please enter a nickname",
        username: "Username",
        nickname: "Nickname",

        /* views/config */
        invalidPageTitle: "Invalid page title",
        invalidPageContent: "Invalid page content, please enter valid content",
    },
    "zh-GB": {
        /* Menu */
        dashboard: "控制台",
        content: "内容",
        article: "文章",
        comment: "评论",
        page: "页面",
        managmentCategories: "管理分类",
        tag: "标签",
        customize: "自定义",
        component: "组件",
        setup: "设置",
        basic: "基础",
        email: "Email",
        push: "推送",
        advanced: "高级",
        user: "用户",
        personalInformation: "个人资料",
        /* services/api */
        errorInRequeset: "请求发生错误，请稍后再试",
        /*components/*/
        home: "首页",
        enterContentHere: "在此输入内容",
        /* views */
        DotNetBlog: "DotNetBlog",
        changePassword: "修改密码",
        logoff: "注销",
        userImage: "用户图像",
        greetingUser: "{0} 已登录",
        siteNavigation: "站点导航",
        /* views/dashboard */
        pleaseEnterTitle: "请输入标题",
        pleaseEnterContent: "请输入内容",
        draftWasSavedSuccessfully: "保存草稿成功",
        saveDraftQuickly: "快捷保存草稿",
        title: "标题",
        save: "保存",
        latestComments: "最新评论",
        empty: "无",
        recentDrafts: "文章稿件",
        statistics: "统计",
        numberOfArticlesPublished: "已发表文章数",
        numberOfPagesPublished: "已发表页面数",
        savedDrafts: "文章稿件",
        numberOfPages: "页面稿件",
        approvedComments: "已通过的评论",
        pendingComments: "未经审核的评论",
        junkComments: "垃圾评论",
        /* views/content */
        operationSuccessful: "操作成功",
        toView: "查看",
        add: "新增",
        delete: "删除",
        name: "名称",
        pendingReview: "待审核",
        accepted: "已通过",
        rejected: "已拒绝",
        accept: "通过",
        reject: "拒绝",
        all: "全部",
        pendings: "待审核",
        date: "日期",
        author: "作者",
        status: "状态",
        pleaseEnterCategoryName: "请输入分类名称",
        description: "描述",
        editCategory: "编辑分类",
        addCategory: "添加分类",
        pleaseEnterPageTitle: "请输入页面标题",
        pleaseEnterPageContent: "请输入页面内容",
        theTitleOfArticle: "文章的标题",
        alias_optional: "别名(可选)",
        keywords: "关键词",
        pageDescription: "页面描述",
        publish: "发布",
        cancel: "取消",
        cancelThePublish: "取消发布",
        goToThePage: "转到页面",
        parent: "上级",
        setAsHomePage: "是否为首页",
        isDisplayedInTheList: "在列表中显示",
        pleaseEnterTheName: "请输入名称",
        editTheTag: "编辑标签",
        enterTheTitleOfArticle: "请输入文章标题",
        enterTheContentOfArticle: "请输入文章标题",
        allowComment: "允许评论",
        summary: "摘要",
        goToArticle: "转到文章",
        category: "分类",
        showAlias: "显示别名",
        showSummary: "显示摘要",
        showDate: "显示日期",
        draft: "草稿",
        sorting: "排序",
        published: "已发布",
        pleaseFillInTheReply: "请填写回复内容",
        reply: "回复",
        replyToComment: "回复评论",
        time: "时间",
        /* view/user */
        pleaseTypeYourEmail: "请输入邮箱",
        pleaseTypeCorrectEmailAddress: "请输入正确的邮箱地址",
        pleaseEnterNickname: "请输入昵称",
        username: "用户名",
        nickname: "昵称",

        /* views/config */
        invalidPageTitle: "请输入错误页面标题",
        invalidPageContent: "",
    }
});
Localization.setLanguage(user.lang);

String.prototype.L = function (...values) {
    return Localization.formatString(Localization[this] || this, values);
}

module.exports = Localization;