import LocalizedStrings from 'react-localization';

const Localization = new LocalizedStrings({
    "en-GB": {
        editorLang: "en",
        /* Menu */
        dashboard: "Dashboard",
        content: "Content",
        article: "Article",
        comment: "Comment",
        page: "Page",
        managmentCategories: "Managment categories",
        tag: "Tag",
        customize: "Customize",
        component: "Component",
        setup: "Setup",
        basic: "Basic",
        email: "Email",
        push: "Push",
        advanced: "Advanced",
        user: "User",
        personalInformation: "Personal Information",
        /* services/api */
        errorInRequeset: "Request an error. Please try again later",
        /* components/bootstrap/* */
        home: "Home",
        enterContentHere: "Enter the content here",
        /* views */
        DotNetBlog: "DotNetBlog",
        changePassword: "Change password",
        logoff: "Logoff",
        userImage: "User Image",
        greetingUser: "Welcome {0}",
        siteNavigation: "Site navigation",
        /* views/dashboard */
        pleaseEnterTitle: "Please enter the title",
        pleaseEnterContent: "Please enter the content",
        draftWasSavedSuccessfully: "Draft was saved successfully",
        saveDraftQuickly: "Save the draft quickly",
        title: "Title",
        save: "Save",
        latestComments: "Latest comments",
        empty: "Empty",
        recentDrafts: "Recent drafts",
        statistics: "Statistics",
        numberOfArticlesPublished: "Number of articles published",
        numberOfPagesPublished: "Number of pages published",
        savedDrafts: "Saved drafts",
        numberOfPages: "Number of pages",
        approvedComments: "Approved comments",
        pendingComments: "Pending comments",
        junkComments: "Junk comments",
        /* views/content */
        operationSuccessful: "Operation successful",
        toView: "To View",
        add: "Add",
        name: "Name",
        pendingReview: "Pending for review",
        accepted: "Accepted",
        rejected: "Rejected",
        accept: "Accept",
        reject: "Reject",
        all: "All",
        pendings: "Pendings",
        date: "Date",
        author: "author",
        status: "Status",
        pleaseEnterCategoryName: "Please enter a category name",
        description: "Description",
        editCategory: "Edit category",
        addCategory: "Add category",
        pleaseEnterPageTitle: "Please enter the page title",
        pleaseEnterPageContent: "Please enter the page content",
        theTitleOfArticle: "The title of the article",
        alias_optional: "Alias(optional)",
        keywords: "Keywords",
        pageDescription: "Page description",
        publish: "Publish",
        cancel: "Cancel",
        cancelThePublish: "Cancel the publish",
        goToThePage: "Go to the page",
        parent: "Parent",
        setAsHomePage: "Set as homepage",
        isDisplayedInTheList: "Is displayed in the list",
        pleaseEnterTheName: "Please enter the name",
        editTheTag: "Edit the tag",
        enterTheTitleOfArticle: "Please enter the title of the article",
        enterTheContentOfArticle: "Please enter the content of the article",
        allowComment: "Allow comment",
        summary: "Summary",
        goToArticle: "Go to article",
        category: "Category",
        showAlias: "Show alias",
        showSummary: "Show summary",
        showDate: "Show date",
        draft: "Draft",
        sorting: "Sorting",
        published: "Published",
        pleaseFillInTheReply: "Please fill in the reply",
        reply: "Reply",
        replyToComment: "Reply to comment",
        time: "Time",
        /* view/user */
        pleaseTypeYourEmail: "Please type your email",
        pleaseTypeCorrectEmailAddress: "Please type correct email address",
        pleaseEnterNickname: "Please enter a nickname",
        username: "Username",
        nickname: "Nickname",

        /* views/config */
        invalidPageTitle: "Invalid page title",
        invalidPageContent: "Invalid page content, please enter valid content",
        errorPage: "Error page",
        errorPageTitle: "Error page title",
        errorPageContent: "Content of the error page",
        customCode: "Custom code",
        headerScript: "Header script",
        footerScript: "footer script",
        enterBlogAddress: "Enter the blog address(URL)",
        enterCorrectNumberOfArticles: "Please enter the correct number of articles",
        blogAddress: "Blog address",
        numberOfArticlesPerPage: "Number of articles per page",
        showOnlyArticleSummary: "Show only article summary",
        never: "Never",
        numericDay: {
            1: "a day",
            default: "{0} days"
        },
        verifyComment: "Verfiy comment",
        trustAuthenticatedCommentsUsers: "Trust authenticated comment's users",
        enableWebsiteComment: "Enable website comment",
        closeCommentAfter: "Close comment after",
        savedSuccessfully: "Saved successfully",
        testSuccessfully: "Test successfully",
        emailAddress: "Email address",
        smtpAddress: "SMTP address",
        enterCorrectPortNumber: "Please enter correct port number",
        portNumber: "Port number",
        enableSSL: "Enable SSL",
        sendEmailWhenComment: "Send notification via email when received a comment",
        testEmailSettings: "Test email settings",
        password: "Password",
        /* views/widget */
        modifyConfiguration: "Modify the configuration",
        showRssButton: "Show RSS Button",
        showNumberOfArticle: "Show the number of articles",
        pleaseEnterNumberOfComment: "Please enter number of comments",
        pleaseEnterCorrectNumberOfComments: "Please enter correct number of comments",
        showNumberOfComments: "Show the number of comments",
        pleaseEnterNumberOfArticles: "Please enter the number of articles",
        pleaseEnterCorrectNumberOfArticles: "Please enter correct number of comments",
        showNumberOfArticles: "Show the number of articles",
        chooseCategory: "Choose category",
        minimumNumberOfArticlesPerTag: "Minimum number of articles per tag",
        maximumNumberOfTagClouds: "Maximum number of tag in clouds",
        noLimitation: "No limitation",
        edit: "Edit",
        remove: "Remove",
        afterAllOperationCompleted: "After all the operations have been completed, the Save button will take effect",
        availableWidgets: "Available widgets",
        addTo: "Add to",
        info: "Info",
        inUse: "In use",
    },
    "zh-CN": {
        editorLang: "zh-CN",
        /* Menu */
        dashboard: "控制台",
        content: "内容",
        article: "文章",
        comment: "评论",
        page: "页面",
        managmentCategories: "管理分类",
        tag: "标签",
        customize: "自定义",
        component: "组件",
        setup: "设置",
        basic: "基础",
        email: "Email",
        push: "推送",
        advanced: "高级",
        user: "用户",
        personalInformation: "个人资料",
        /* services/api */
        errorInRequeset: "请求发生错误，请稍后再试",
        /*components/*/
        home: "首页",
        enterContentHere: "在此输入内容",
        /* views */
        DotNetBlog: "DotNetBlog",
        changePassword: "修改密码",
        logoff: "注销",
        userImage: "用户图像",
        greetingUser: "{0} 已登录",
        siteNavigation: "站点导航",
        /* views/dashboard */
        pleaseEnterTitle: "请输入标题",
        pleaseEnterContent: "请输入内容",
        draftWasSavedSuccessfully: "保存草稿成功",
        saveDraftQuickly: "快捷保存草稿",
        title: "标题",
        save: "保存",
        latestComments: "最新评论",
        empty: "无",
        recentDrafts: "文章稿件",
        statistics: "统计",
        numberOfArticlesPublished: "已发表文章数",
        numberOfPagesPublished: "已发表页面数",
        savedDrafts: "文章稿件",
        numberOfPages: "页面稿件",
        approvedComments: "已通过的评论",
        pendingComments: "未经审核的评论",
        junkComments: "垃圾评论",
        /* views/content */
        operationSuccessful: "操作成功",
        toView: "查看",
        add: "新增",
        delete: "删除",
        name: "名称",
        pendingReview: "待审核",
        accepted: "已通过",
        rejected: "已拒绝",
        accept: "通过",
        reject: "拒绝",
        all: "全部",
        pendings: "待审核",
        date: "日期",
        author: "作者",
        status: "状态",
        pleaseEnterCategoryName: "请输入分类名称",
        description: "描述",
        editCategory: "编辑分类",
        addCategory: "添加分类",
        pleaseEnterPageTitle: "请输入页面标题",
        pleaseEnterPageContent: "请输入页面内容",
        theTitleOfArticle: "文章的标题",
        alias_optional: "别名(可选)",
        keywords: "关键词",
        pageDescription: "页面描述",
        publish: "发布",
        cancel: "取消",
        cancelThePublish: "取消发布",
        goToThePage: "转到页面",
        parent: "上级",
        setAsHomePage: "是否为首页",
        isDisplayedInTheList: "在列表中显示",
        pleaseEnterTheName: "请输入名称",
        editTheTag: "编辑标签",
        enterTheTitleOfArticle: "请输入文章标题",
        enterTheContentOfArticle: "请输入文章标题",
        allowComment: "允许评论",
        summary: "摘要",
        goToArticle: "转到文章",
        category: "分类",
        showAlias: "显示别名",
        showSummary: "显示摘要",
        showDate: "显示日期",
        draft: "草稿",
        sorting: "排序",
        published: "已发布",
        pleaseFillInTheReply: "请填写回复内容",
        reply: "回复",
        replyToComment: "回复评论",
        time: "时间",
        /* view/user */
        pleaseTypeYourEmail: "请输入邮箱",
        pleaseTypeCorrectEmailAddress: "请输入正确的邮箱地址",
        pleaseEnterNickname: "请输入昵称",
        username: "用户名",
        nickname: "昵称",

        /* views/config */
        invalidPageTitle: "请输入错误页面标题",
        invalidPageContent: "请输入错误页面内容",
        errorPage: "错误页面",
        errorPageTitle: "错误页面的标题",
        errorPageContent: "错误页面的内容",
        customCode: "自定义代码",
        headerScript: "头部区域",
        footerScript: "底部区域",
        enterBlogAddress: "请输入博客地址",
        enterCorrectNumberOfArticles: "请输入正确的文章数量",
        blogAddress: "博客地址",
        numberOfArticlesPerPage: "每页文章数",
        showOnlyArticleSummary: "仅显示文章摘要",
        never: "从不",
        numericDay: {
            default: "{0}天"
        },
        verifyComment: "审核评论",
        trustAuthenticatedCommentsUsers: "信任已通过验证的评论作者",
        enableWebsiteComment: "在评论中启用网站",
        closeCommentAfter: "之后关闭评论",
        savedSuccessfully: "保存成功",
        testSuccessfully: "测试成功",
        emailAddress: "Email地址",
        smtpAddress: "SMTP address",
        enterCorrectPortNumber: "请输入正确的端口号",
        portNumber: "端口号",
        enableSSL: "启用SSL",
        sendEmailWhenComment: "发送评论邮件",
        testEmailSettins: "测试邮件配置",
        password: "密码",
        /* views/widget */
        modifyConfiguration: "修改配置",
        showRssButton: "显示RSS按钮",
        showNumberOfArticle: "显示文章数",
        pleaseEnterNumberOfComment: "请输入评论数目",
        pleaseEnterCorrectNumberOfComments: "请输入正确的评论数量",
        showNumberOfComments: "显示评论数目",
        pleaseEnterNumberOfArticles: "请输入文章数目",
        pleaseEnterCorrectNumberOfArticles: "请输入正确的文章数量",
        chooseCategory: "选择分类",
        minimumNumberOfArticlesPerTag: "每个标签的最小文章数量",
        maximumNumberOfTagClouds: "标签云的最大数量",
        noLimitation: "不限制",
        edit: "编辑",
        remove: "移除",
        afterAllOperationCompleted: "所有操作完毕后，点保存按钮才会生效",
        availableWidgets: "可用组件",
        addTo: "增加",
        info: "信息",
        inUse: "正在使用",
    }
});
Localization.setLanguage(user.lang);

String.prototype.L = function (...values) {
    var l = Localization[this] || this;
    if (l instanceof Object) {
        var num = values[0] || "default";
        return Localization.formatString(l[num] || l["default"], values);
    }
    else 
        return Localization.formatString(l, values);
}

module.exports = Localization;